uploads = []
generated = []

[[outputs]]
id = "hLizkZfnxbbxwi2-9ioRY"
uri = "file://app/build/outputs/apk/debug/app-debug.tar.gz"
type = "unspecified"
title = "app-debug.apk (tar.gz) — 8 Ball Pool Mod"

[[outputs]]
id = "FGovR52nbfuYgiIbygwK2"
uri = "file://app/build/outputs/apk/debug/app-debug-v2.tar.gz"
type = "unspecified"
title = "app-debug-v2.apk — 8BP Mod (semua perubahan)"
