uploads = []
generated = []

[[outputs]]
id = "qyemuE0RlETMvGwrY7iKk"
uri = "file://library_arm64-v8a.zip"
type = "unspecified"
title = "library.so — arm64-v8a build (8BP Mod)"

[[outputs]]
id = "J_oO2fTFbSHUs74xOgxGE"
uri = "file://FluxProEngine8BP.zip"
type = "unspecified"
title = "FluxProEngine8BP - library.so (arm64-v8a)"

[[outputs]]
id = "u7av_CSTbIvU9aBNJ0e9q"
uri = "file://FluxProEngine8BP_LYN4XP.zip"
type = "unspecified"
title = "FluxProEngine8BP - @LYN4XP (arm64-v8a)"

[[outputs]]
id = "MQrj1JlR87OmqQqSm8CVr"
uri = "file://FluxProEngine8BP_EnemyLine.zip"
type = "unspecified"
title = "FluxProEngine8BP + Enemy Line (arm64-v8a)"

[[outputs]]
id = "SlZeWUBKgEcXPyMk6W7s4"
uri = "file://library_arm64.zip"
type = "unspecified"
title = "library.so — Fixed Build (arm64-v8a)"

[[outputs]]
id = "KqTGvBNlgMv-CrdYkJKIc"
uri = "file://library_autoaim.zip"
type = "unspecified"
title = "library.so — AutoAim Build (arm64-v8a)"

[[outputs]]
id = "HcVsMWzbji2H5verZW6dL"
uri = "file://app/build/outputs/apk/debug/FluxProEngine_GlassUI.tar.gz"
type = "unspecified"
title = "Flux Pro Engine — Glass UI Build (app-debug.apk)"

[[outputs]]
id = "DZlYGfA0dzogyqadv6fKQ"
uri = "file://app/build/outputs/apk/debug/FluxProEngine_RedGlass.tar.gz"
type = "unspecified"
title = "Flux Pro Engine — Red Glass Theme (app-debug.apk)"
